### ISSUE TITLE
Scaling and Rotating R image

### ISSUE THREAD

**Issue by hahazhar** [amcquistan/affine-image-transforms-python#1]
Hi when i tried running the code on jupyter, I am unable to obtain the 
"rotated 90 degrees clockwise and scaled up 2X. However, the result is now obviously diminished as you can easily see discontinuity in the pixel intensities."

For me it shows up as a blank image. 
I am using Python 3

Do you have any idea what might be the issue?
Hope to hear from you soon!

**Comment by hahazhar** [comment]
The data type of the image needs to correspond with the initialisation of the NumPy array. Once they tally, it should work

**Comment by daaoutt** [comment]
> The data type of the image needs to correspond with the initialisation of the NumPy array. Once they tally, it should work

What that means?
